services:
  - type: web
    name: ai-resume-portal
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ADMIN_URL
        value: secure-admin-2024
      - key: ADMIN_ENABLED
        value: True
      - key: RENDER
        value: True
      - key: DATABASE_URL
        fromDatabase:
          name: ai-resume-db
          property: connectionString

databases:
  - name: ai-resume-db
    databaseName: ai_resume_db
    user: ai_resume_user
