services:
  - type: web
    name: ai-resume-portal
    env: python
    rootDir: ai_resume_portal
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ADMIN_URL
        value: secure-admin-2024
      - key: ADMIN_ENABLED
        value: True
      - key: RENDER
        value: True
